spring:
  datasource:
    url: jdbc:mysql://139.155.150.150:3307/big_event?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1586866@Xyz
mybatis:
  mapper-locations: classpath:mapper/*.xml
